stages:
  - test
  - build
  - deploy

variables:
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

run_tests:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm run lint || echo "Lint warnings allowed"
    - npm run test -- --run
  only:
    - merge_requests
    - main

build_image:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build 
      --cache-from $REGISTRY_IMAGE:latest 
      -t $REGISTRY_IMAGE:$IMAGE_TAG 
      -t $REGISTRY_IMAGE:latest 
      -f Dockerfile .
    - docker push $REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $REGISTRY_IMAGE:latest
  only:
    - main
    - feature/ui

deploy_local_k8s:
  stage: deploy
  image: bitnami/kubectl:1.27
  script:
    - mkdir -p ~/.kube
    - cp "$KUBECONFIG" ~/.kube/config
    - kubectl set image deployment/neocentra-mfe-shared shared-mfe=$REGISTRY_IMAGE:$IMAGE_TAG --record
    - kubectl rollout status deployment/neocentra-mfe-shared
  only:
    - main
    - feature/ui
